---
title: "06_analysis_2"
format: html
editor: visual
---

```{r}
#| output: false
library("tidyverse")
library("here")
library("broom")
library("cowplot")
```

## Performing a PCA

```{r}
data <- read_tsv(file = here("data/03_dat_aug.tsv.gz"), 
                 na = "NA", 
                 guess_max = 1001
                 )
```

### Look at the data in PC coordinates

```{r}
data_pivot <- data |>
  pivot_wider(
    names_from = ensembl_id,
    values_from = gene_expression
  )
```

```{r}
pca_fit <- data_pivot |> 
  select(starts_with("ENSG")) |> 
  select(where(~ any(. != 0))) |> 
  prcomp(scale = TRUE)
```

```{r}
pca_fit |> 
  augment(data_pivot) |> 
  filter(abs(.fittedPC1) < 50 & abs(.fittedPC2) < 50) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, color = vital_status)) +
  geom_point(size = 1.5) +
  theme_half_open(12) + background_grid()
```

```{r}
pca_fit |> 
  augment(data_pivot) |> 
  filter(abs(.fittedPC1) < 50 & abs(.fittedPC2) < 50) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = prior_malignancy)) +
  geom_point(size = 1.5) +
  theme_half_open(12) + background_grid()
```

```{r}
pca_fit |> 
  augment(data_pivot) |> 
  filter(abs(.fittedPC1) < 50 & abs(.fittedPC2) < 50) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = cancer_stage)) +
  geom_point(size = 1.5) +
  theme_half_open(12) + background_grid()
```

### Look at the rotation matrix

```{r}
pca_fit |> 
  tidy(matrix = "rotation")
```

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues") |> 
  ggplot(aes(PC, percent)) +
  

```

```{r}
pca_fit |>
  tidy("pcs") |> 
  mutate(percent = percent * 100) |> 
  ggplot(aes(x = PC,
             y = percent)) +
  geom_hline(yintercept = 0) +
  geom_col(colour = "black",
           alpha = 0.5) +
  theme_bw(base_size = 20) +
  theme(panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_blank()) +
  labs(title = "Scree Plot of PCA") +
  coord_cartesian(xlim = c(1, 100), ylim = c(0, 70))
```

```{r}
pca_plot_axes_labels <- pca_fit |>
  tidy("eigenvalues") |>
  mutate(lbl = str_c("PC", PC, ", VE = ", round(percent*100,2), "%")) |> 
  pull("lbl")
pca_plot_axes_labels
```

### Look at the variance explained by each PC

hrhr
